name: Android CI

on:
    workflow_dispatch:
        inputs:
            src:
                description: 'Source directory'
                default: 'app'
            dest:
                description: 'Output directory'
                default: 'app/build/outputs/apk'
            debug:
                description: 'Build in debug mode'
                default: 'true'
            release:
                description: 'Build in release mode'
                default: 'false'

    push:
        branches:
            - main
    pull_request:
        branches: [ $default-branch ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: 21
                  distribution: temurin
                  cache: gradle

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              run: ./gradlew assembleRelease
            - name: Upload to release
              uses: actions/upload-artifact@v4
              with:
                  name: app
                  path: app/build/outputs/apk/release/app-release.apk

    upload:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - uses: actions/download-artifact@v4
            with:
                name: app
                path: dist
          - name: copy static files
            uses: appleboy/scp-action@v0.1.4
            with:
                host: ${{ vars.SSH_HOST }}
                username: ${{ vars.SSH_USER }}
                port: ${{ vars.SSH_PORT }}
                key: ${{ secrets.SSH_KEY }}
                overwrite: true
                source: "dist/*"
                target: "~/${{ github.repository_owner }}/caddy/static/${{ github.repository }}/"
